spring.application.name: avion-service
server:
  port: 9000

# consul
spring.cloud.consul.host: localhost
spring.cloud.consul.port: 8500
spring.cloud.consul.discovery.hostname: localhost
spring.cloud.consul.discovery.register-health-check: false
spring.config.import: optional:consul:localhost:8500

# JPA
spring.jpa.hibernate.ddl-auto: create
spring.jpa.defer-datasource-initialization: true

# binding messaging
spring.cloud.stream:
  function:
    definition: avionService
  bindings:
    avionService-in-0:
      destination: reservation-topic
  kafka:
    bindings:
      avionService-in-0:
        consumer:
          configuration:
            value:
              deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    binder:
      brokers:
        - localhost:9092

